services:
  mysql:
    image: mysql:8.0
    container_name: futfriend-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futfriend
      MYSQL_USER: telmo
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 25s
    networks:
      - futfriend-net

  backend:
    build: .
    container_name: futfriend-backend
    restart: always
    ports:
      - "5500:5500"
    environment:
      PORT: 5500
      DATABASE_URL: "mysql://telmo:1234@mysql:3306/futfriend"
      JWT_SECRET: "supersecretjwt"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/node_modules/.prisma
    networks:
      - futfriend-net

networks:
  futfriend-net:
    driver: bridge

volumes:
  db_data:
