version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: futfriend-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futfriend
      MYSQL_USER: telmo
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - futfriend-net

  backend:
    build: .
    container_name: futfriend-backend
    restart: always
    ports:
      - "5500:5500"
    environment:
      DATABASE_URL: "mysql://telmo:1234@mysql:3306/futfriend"
      JWT_SECRET: "chave_super_segura_que_so_tu_sabes"
      PORT: 5500
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - futfriend-net
    volumes:
      - .:/app    # monta o teu c√≥digo local dentro do container para hot reload
      - /app/node_modules  # evita conflito com node_modules local
      - /app/node_modules/.prisma  # evita conflito com prisma

networks:
  futfriend-net:
    driver: bridge